# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QGVAPlayerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QGVAPlayerDemo
pod 'WoodPeckeriOS', :configurations => ['Debug']

# for macOS project
# pod 'WoodpeckerMacOS', :configurations => ['Debug']
  target 'QGVAPlayerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QGVAPlayerDemoUITests' do
    # Pods for testing
  end

end
